# docker build -f src/main/docker/Dockerfile.jvm -t carl/notion:v1.0.0 .

FROM eclipse-temurin:17.0.11_9-jre-alpine

ENV LANGUAGE='zh_CN:zh'

COPY --chown=185 build/libs/ /app/

EXPOSE 8080
USER 185

CMD ["java", "-jar", "/app/blog-0.0.1-SNAPSHOT.jar"]